>>>
>>> from django.contrib.auth.models import User
>>> e1 = Event(title='Lunch', description='Indian Lunch at 1400h', chef = User.objects.get(username='john'))
>>> e1.save()
>>> r1 = Review(comment='Good Indian Food', event=e1, reviewer = User.objects.get(username='rajat'))
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'Review' is not defined
>>> from food.models import Review
>>> r1 = Review(comment='Good Indian Food', event=e1, reviewer = User.objects.get(username='rajat'))
>>> r1.save()
>>> r2 = Review(comment='Bad Shit', event=e1, reviewer = User.objects.get(username='chris'))
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/manager.py", line 151, in get
    return self.get_queryset().get(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 307, in get
    self.model._meta.object_name)
DoesNotExist: User matching query does not exist.
>>> r2 = Review(comment='Bad Shit', event=e1, reviewer = User.objects.get(username='john'))
>>> r2.save()
>>> e1.review_set
<django.db.models.fields.related.RelatedManager object at 0xab4716c>
>>> e1.review_set()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
TypeError: 'RelatedManager' object is not callable
>>> e1.review_set.all()
[<Review: Good Indian Food>, <Review: Bad Shit>]
>>> exit()
root@rajat-VirtualBox:~/Documents/Workspace/RCT/fooding/fooding# cd ..
root@rajat-VirtualBox:~/Documents/Workspace/RCT/fooding# history | grep chmod
   54  chmod -R rajat:rajat /home/rajat/project/testProject
   55  chmod -R --help
   58  chmod -R 755 testProject
  295  chmod -R 777 fooding/
  302  chmod -R 777 fooding/
  432  history | grep chmod
root@rajat-VirtualBox:~/Documents/Workspace/RCT/fooding# cd ..
root@rajat-VirtualBox:~/Documents/Workspace/RCT# ls -lt
total 4
drwxrwxrwx 3 root root 4096 Apr  5 23:54 fooding
root@rajat-VirtualBox:~/Documents/Workspace/RCT# chown -R rajat fooding/
root@rajat-VirtualBox:~/Documents/Workspace/RCT# ls -lt
total 4
drwxrwxrwx 3 rajat root 4096 Apr  5 23:54 fooding
root@rajat-VirtualBox:~/Documents/Workspace/RCT# chgrp -R rajat fooding/
root@rajat-VirtualBox:~/Documents/Workspace/RCT# ls -lt
total 4
drwxrwxrwx 3 rajat rajat 4096 Apr  5 23:54 fooding
root@rajat-VirtualBox:~/Documents/Workspace/RCT# pwd
/root/Documents/Workspace/RCT
root@rajat-VirtualBox:~/Documents/Workspace/RCT# cd ..
root@rajat-VirtualBox:~/Documents/Workspace# cp -r RCT /home/rajat/
root@rajat-VirtualBox:~/Documents/Workspace# cd /home/rajat/
root@rajat-VirtualBox:/home/rajat# la
ls: cannot access .gvfs: Permission denied

>>> User.objects.get_queryset()
[<User: cmarques>, <User: chris>, <User: tonysoprano>, <User: soukaina>, <User: boris>, <User: rajhub>, <User: jon>, <User: cyprien>, <User: dan>, <User: cyp>]
>>> User.objects.get(username="rajhub")
<User: rajhub>
>>> u1 = User.objects.get(username="rajhub")
>>> u1.event_set.all()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'User' object has no attribute 'event_set'
>>> u1.event_
u1.event_chef    u1.event_guests  u1.event_liker
>>> u1.event_chef.all()
[<Event: going to cook some delicious stuff!>, <Event: Pasta and Pizza>, <Event: Typical Swedish Expensive Dinner>]


